import Foundation

enum SmartSupplyLocalizationResources {
    // These declarations give String Catalog extraction stable semantic keys and
    // English source values. Runtime lookup is performed through L10n.text.
    static let values: [LocalizedStringResource] = [
        LocalizedStringResource("smart_supply.recommended.title", defaultValue: "Recommended", comment: "Heading for app recommendations"),
        LocalizedStringResource("smart_supply.recommended.detail", defaultValue: "Recommendations combine basic preparedness, the selected emergency, and your household profile. They are planning guidance, not a guarantee of safety.", comment: "Smart list explanation"),
        LocalizedStringResource("smart_supply.home.title", defaultValue: "Home preparedness", comment: "Supplies for remaining at home"),
        LocalizedStringResource("smart_supply.grab.title", defaultValue: "Grab / evacuation", comment: "Supplies prepared for leaving quickly"),
        LocalizedStringResource("smart_supply.my_supplies.title", defaultValue: "My supplies", comment: "Heading for persisted user supply records"),
        LocalizedStringResource("smart_supply.my_supplies.detail", defaultValue: "Items you have recorded. Recommendations never change quantities, packed status, or review dates.", comment: "Persistence distinction"),
        LocalizedStringResource("smart_supply.my_supplies.empty", defaultValue: "No saved supplies yet.", comment: "Empty saved supply list"),
        LocalizedStringResource("smart_supply.appears_recorded", defaultValue: "Recorded", comment: "Exact-name match only; does not claim ownership"),
        LocalizedStringResource("smart_supply.quantity", defaultValue: "Quantity", comment: "Saved supply quantity label"),
        LocalizedStringResource("smart_supply.priority.critical", defaultValue: "Critical priority", comment: "Highest planning priority"),
        LocalizedStringResource("smart_supply.priority.high", defaultValue: "High priority", comment: "High planning priority"),
        LocalizedStringResource("smart_supply.priority.normal", defaultValue: "Normal priority", comment: "Normal planning priority"),
        LocalizedStringResource("smart_supply.safety.general", defaultValue: "Prepare in advance and follow current instructions from emergency services and public authorities.", comment: "General supply safety notice"),
        LocalizedStringResource("smart_supply.safety.house_fire", defaultValue: "During an active fire, leave immediately. Never delay evacuation to collect supplies or belongings.", comment: "Safety-critical active fire notice"),
        LocalizedStringResource("smart_supply.safety.authority_first", defaultValue: "Current authority instructions determine whether to shelter or evacuate. This supply list does not make that decision.", comment: "Authority-first security incident notice"),

        LocalizedStringResource("supply.water", defaultValue: "Drinking water", comment: "Home preparedness supply"),
        LocalizedStringResource("supply.shelfStableFood", defaultValue: "Shelf-stable food", comment: "Home preparedness supply"),
        LocalizedStringResource("supply.cookingMethod", defaultValue: "Cooking method without normal power", comment: "Home preparedness supply"),
        LocalizedStringResource("supply.warmth", defaultValue: "Warm clothing and blankets", comment: "Home preparedness supply"),
        LocalizedStringResource("supply.lighting", defaultValue: "Battery lighting", comment: "Home preparedness supply"),
        LocalizedStringResource("supply.batteryLighting", defaultValue: "Battery lighting", comment: "Legacy template supply"),
        LocalizedStringResource("supply.radio", defaultValue: "Battery or crank radio", comment: "Home preparedness supply"),
        LocalizedStringResource("supply.batteries", defaultValue: "Batteries", comment: "Home preparedness supply"),
        LocalizedStringResource("supply.powerBank", defaultValue: "Power banks", comment: "Home preparedness supply"),
        LocalizedStringResource("supply.medicines", defaultValue: "Necessary medicines", comment: "Preparedness supply"),
        LocalizedStringResource("supply.firstAid", defaultValue: "First aid supplies", comment: "Home preparedness supply"),
        LocalizedStringResource("supply.hygiene", defaultValue: "Hygiene supplies", comment: "Home preparedness supply"),
        LocalizedStringResource("supply.hygieneSupplies", defaultValue: "Hygiene supplies", comment: "Legacy template supply"),
        LocalizedStringResource("supply.paymentPreparedness", defaultValue: "Payment preparedness", comment: "Home preparedness supply"),
        LocalizedStringResource("supply.paymentOptions", defaultValue: "Payment options", comment: "Legacy template supply"),
        LocalizedStringResource("supply.petHomeSupplies", defaultValue: "Pet food, water, and supplies", comment: "Pet home preparedness"),
        LocalizedStringResource("supply.childHomeSupplies", defaultValue: "Essential child supplies", comment: "Child home preparedness"),
        LocalizedStringResource("supply.woodStoveFuel", defaultValue: "Dry firewood and matches", comment: "Wood stove preparedness"),
        LocalizedStringResource("supply.gasInstallationSupplies", defaultValue: "Gas installation preparedness", comment: "Only shown for explicit gas installations"),
        LocalizedStringResource("supply.essentialSupportSupplies", defaultValue: "Essential support supplies", comment: "Special assistance household supply"),
        LocalizedStringResource("supply.alternativeHeatingPreparedness", defaultValue: "Alternative heating preparedness", comment: "Home preparedness supply"),
        LocalizedStringResource("supply.identification", defaultValue: "Identification", comment: "Grab list supply"),
        LocalizedStringResource("supply.assistiveDevices", defaultValue: "Assistive devices", comment: "Grab list supply"),
        LocalizedStringResource("supply.phone", defaultValue: "Mobile phone", comment: "Grab list supply"),
        LocalizedStringResource("supply.chargerPowerBank", defaultValue: "Charger and power bank", comment: "Grab list supply"),
        LocalizedStringResource("supply.phoneAndCharger", defaultValue: "Phone, charger, and power bank", comment: "Legacy template supply"),
        LocalizedStringResource("supply.warmClothing", defaultValue: "Warm clothing", comment: "Grab list supply"),
        LocalizedStringResource("supply.grabFood", defaultValue: "Food for evacuation", comment: "Grab list supply"),
        LocalizedStringResource("supply.foodAndDrink", defaultValue: "Food and drink", comment: "Legacy template supply"),
        LocalizedStringResource("supply.drinkingWater", defaultValue: "Drinking water for evacuation", comment: "Grab list supply"),
        LocalizedStringResource("supply.bankCards", defaultValue: "Bank cards", comment: "Grab list supply"),
        LocalizedStringResource("supply.cash", defaultValue: "Cash", comment: "Grab list supply"),
        LocalizedStringResource("supply.documentCopies", defaultValue: "Critical document copies", comment: "Grab list supply"),
        LocalizedStringResource("supply.childEvacuationSupplies", defaultValue: "Essential child evacuation supplies", comment: "Child grab list"),
        LocalizedStringResource("supply.petEvacuationSupplies", defaultValue: "Essential pet evacuation supplies", comment: "Pet grab list"),
        LocalizedStringResource("supply.assistanceInformation", defaultValue: "Assistance needs information", comment: "Special assistance grab list"),
        LocalizedStringResource("supply.evChargingPlan", defaultValue: "EV charging and route plan", comment: "Does not imply EV is preferred transport")
    ]
}
